<?php
/**
 * @package   Phpno1\Test\DataStructure
 * @author    Yaha <1143990204@qq.com>
 * @link      https://blog.flyaha.top
 */

namespace Phpno1\Test\DataStructure;

use Phpno1\Algorithm\DataStructure\Base\Stack;
use PHPUnit\Framework\TestCase;

class StackTest extends TestCase
{

    private $stack;

    public function setUp()
    {
        $this->stack = new Stack();

        $i = 0;
        while ($i < 10) {
            $this->stack->push("Stack" . $i);

            $i++;
        }

//        var_dump($this->stack);

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @test
     */
    public function not_empty_test()
    {
        $this->assertFalse($this->stack->isEmpty());
    }

    /**
     * @test
     */
    public function empty_test()
    {
        $i = 0;
        while ($i < 10) {
            $this->stack->pop();

            $i++;
        }
        $this->assertTrue($this->stack->isEmpty());
    }
}